version: "3.8"
services:
  tendermint:
    image: tendermint/tendermint:v0.33.8
    # image: tendermint/tendermint
    command: node --proxy_app=tcp://kvstore-app:26658
    # command: node --proxy_app=kvstore --consensus.create_empty_blocks=false --rpc.laddr="tcp://0.0.0.0:26657"
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26660:26660"
    volumes:
      - $PWD/hayoola:/tendermint
      # - $PWD/rings:/rings
      # - $PWD/new-rings:/new-rings
    depends_on:
      - kvstore-app

  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  kvstore-app:
    build: .
    ports:
      - "26658:26658"
    environment:
      RINGS_PATH: "/rings"
      RPC_BASEURL: "http://tendermint:26657"
      RINGS_WRITE_PATH: "/new-rings"
