global:
  scrape_interval:     15s
  external_labels:
    monitor: 'monster'
scrape_configs:
  - job_name: 'prometheus'   
    scrape_interval: 5s
    static_configs:
      - targets: ['tendermint:26660']
