# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/privval/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.third_party.proto.gogoproto import gogo_pb2 as third__party_dot_proto_dot_gogoproto_dot_gogo__pb2
from tendermint.proto.crypto.keys import types_pb2 as proto_dot_crypto_dot_keys_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/privval/types.proto',
  package='tendermint.proto.privval',
  syntax='proto3',
  serialized_options=_b('Z.github.com/tendermint/tendermint/proto/privval'),
  serialized_pb=_b('\n\x19proto/privval/types.proto\x12\x18tendermint.proto.privval\x1a&third_party/proto/gogoproto/gogo.proto\x1a\x1dproto/crypto/keys/types.proto\"\xb1\x01\n\tFilePVKey\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12>\n\x07pub_key\x18\x02 \x01(\x0b\x32\'.tendermint.proto.crypto.keys.PublicKeyB\x04\xc8\xde\x1f\x00\x12@\n\x08priv_key\x18\x03 \x01(\x0b\x32(.tendermint.proto.crypto.keys.PrivateKeyB\x04\xc8\xde\x1f\x00\x12\x11\n\tfile_path\x18\x04 \x01(\t\"|\n\x13\x46ilePVLastSignState\x12\x0e\n\x06height\x18\x01 \x01(\x03\x12\r\n\x05round\x18\x02 \x01(\x03\x12\x0c\n\x04step\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x12\n\nsign_bytes\x18\x05 \x01(\x0c\x12\x11\n\tfile_path\x18\x06 \x01(\tB0Z.github.com/tendermint/tendermint/proto/privvalb\x06proto3')
  ,
  dependencies=[third__party_dot_proto_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,proto_dot_crypto_dot_keys_dot_types__pb2.DESCRIPTOR,])




_FILEPVKEY = _descriptor.Descriptor(
  name='FilePVKey',
  full_name='tendermint.proto.privval.FilePVKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='tendermint.proto.privval.FilePVKey.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='tendermint.proto.privval.FilePVKey.pub_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priv_key', full_name='tendermint.proto.privval.FilePVKey.priv_key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='tendermint.proto.privval.FilePVKey.file_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=304,
)


_FILEPVLASTSIGNSTATE = _descriptor.Descriptor(
  name='FilePVLastSignState',
  full_name='tendermint.proto.privval.FilePVLastSignState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='tendermint.proto.privval.FilePVLastSignState.height', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='tendermint.proto.privval.FilePVLastSignState.round', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='tendermint.proto.privval.FilePVLastSignState.step', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='tendermint.proto.privval.FilePVLastSignState.signature', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign_bytes', full_name='tendermint.proto.privval.FilePVLastSignState.sign_bytes', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='tendermint.proto.privval.FilePVLastSignState.file_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=430,
)

_FILEPVKEY.fields_by_name['pub_key'].message_type = proto_dot_crypto_dot_keys_dot_types__pb2._PUBLICKEY
_FILEPVKEY.fields_by_name['priv_key'].message_type = proto_dot_crypto_dot_keys_dot_types__pb2._PRIVATEKEY
DESCRIPTOR.message_types_by_name['FilePVKey'] = _FILEPVKEY
DESCRIPTOR.message_types_by_name['FilePVLastSignState'] = _FILEPVLASTSIGNSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilePVKey = _reflection.GeneratedProtocolMessageType('FilePVKey', (_message.Message,), dict(
  DESCRIPTOR = _FILEPVKEY,
  __module__ = 'proto.privval.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.privval.FilePVKey)
  ))
_sym_db.RegisterMessage(FilePVKey)

FilePVLastSignState = _reflection.GeneratedProtocolMessageType('FilePVLastSignState', (_message.Message,), dict(
  DESCRIPTOR = _FILEPVLASTSIGNSTATE,
  __module__ = 'proto.privval.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.privval.FilePVLastSignState)
  ))
_sym_db.RegisterMessage(FilePVLastSignState)


DESCRIPTOR._options = None
_FILEPVKEY.fields_by_name['pub_key']._options = None
_FILEPVKEY.fields_by_name['priv_key']._options = None
# @@protoc_insertion_point(module_scope)
