# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types/proto3/block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types/proto3/block.proto',
  package='tendermint.types.proto3',
  syntax='proto3',
  serialized_options=_b('Z-github.com/tendermint/tendermint/types/proto3'),
  serialized_pb=_b('\n\x18types/proto3/block.proto\x12\x17tendermint.types.proto3\",\n\rPartSetHeader\x12\r\n\x05Total\x18\x01 \x01(\x05\x12\x0c\n\x04Hash\x18\x02 \x01(\x0c\"T\n\x07\x42lockID\x12\x0c\n\x04Hash\x18\x01 \x01(\x0c\x12;\n\x0bPartsHeader\x18\x02 \x01(\x0b\x32&.tendermint.types.proto3.PartSetHeader\"\x93\x03\n\x06Header\x12\x31\n\x07Version\x18\x01 \x01(\x0b\x32 .tendermint.types.proto3.Version\x12\x0f\n\x07\x43hainID\x18\x02 \x01(\t\x12\x0e\n\x06Height\x18\x03 \x01(\x03\x12\x30\n\x04Time\x18\x04 \x01(\x0b\x32\".tendermint.types.proto3.Timestamp\x12\x35\n\x0bLastBlockID\x18\x05 \x01(\x0b\x32 .tendermint.types.proto3.BlockID\x12\x16\n\x0eLastCommitHash\x18\x06 \x01(\x0c\x12\x10\n\x08\x44\x61taHash\x18\x07 \x01(\x0c\x12\x16\n\x0eValidatorsHash\x18\x08 \x01(\x0c\x12\x1a\n\x12NextValidatorsHash\x18\t \x01(\x0c\x12\x15\n\rConsensusHash\x18\n \x01(\x0c\x12\x0f\n\x07\x41ppHash\x18\x0b \x01(\x0c\x12\x17\n\x0fLastResultsHash\x18\x0c \x01(\x0c\x12\x14\n\x0c\x45videnceHash\x18\r \x01(\x0c\x12\x17\n\x0fProposerAddress\x18\x0e \x01(\x0c\"%\n\x07Version\x12\r\n\x05\x42lock\x18\x01 \x01(\x04\x12\x0b\n\x03\x41pp\x18\x02 \x01(\x04\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x42/Z-github.com/tendermint/tendermint/types/proto3b\x06proto3')
)




_PARTSETHEADER = _descriptor.Descriptor(
  name='PartSetHeader',
  full_name='tendermint.types.proto3.PartSetHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Total', full_name='tendermint.types.proto3.PartSetHeader.Total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hash', full_name='tendermint.types.proto3.PartSetHeader.Hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=97,
)


_BLOCKID = _descriptor.Descriptor(
  name='BlockID',
  full_name='tendermint.types.proto3.BlockID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hash', full_name='tendermint.types.proto3.BlockID.Hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PartsHeader', full_name='tendermint.types.proto3.BlockID.PartsHeader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=183,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='tendermint.types.proto3.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Version', full_name='tendermint.types.proto3.Header.Version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChainID', full_name='tendermint.types.proto3.Header.ChainID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Height', full_name='tendermint.types.proto3.Header.Height', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time', full_name='tendermint.types.proto3.Header.Time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastBlockID', full_name='tendermint.types.proto3.Header.LastBlockID', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastCommitHash', full_name='tendermint.types.proto3.Header.LastCommitHash', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DataHash', full_name='tendermint.types.proto3.Header.DataHash', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ValidatorsHash', full_name='tendermint.types.proto3.Header.ValidatorsHash', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NextValidatorsHash', full_name='tendermint.types.proto3.Header.NextValidatorsHash', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConsensusHash', full_name='tendermint.types.proto3.Header.ConsensusHash', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppHash', full_name='tendermint.types.proto3.Header.AppHash', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastResultsHash', full_name='tendermint.types.proto3.Header.LastResultsHash', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EvidenceHash', full_name='tendermint.types.proto3.Header.EvidenceHash', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProposerAddress', full_name='tendermint.types.proto3.Header.ProposerAddress', index=13,
      number=14, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=589,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='tendermint.types.proto3.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Block', full_name='tendermint.types.proto3.Version.Block', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='App', full_name='tendermint.types.proto3.Version.App', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=628,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='tendermint.types.proto3.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='tendermint.types.proto3.Timestamp.seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanos', full_name='tendermint.types.proto3.Timestamp.nanos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=673,
)

_BLOCKID.fields_by_name['PartsHeader'].message_type = _PARTSETHEADER
_HEADER.fields_by_name['Version'].message_type = _VERSION
_HEADER.fields_by_name['Time'].message_type = _TIMESTAMP
_HEADER.fields_by_name['LastBlockID'].message_type = _BLOCKID
DESCRIPTOR.message_types_by_name['PartSetHeader'] = _PARTSETHEADER
DESCRIPTOR.message_types_by_name['BlockID'] = _BLOCKID
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PartSetHeader = _reflection.GeneratedProtocolMessageType('PartSetHeader', (_message.Message,), dict(
  DESCRIPTOR = _PARTSETHEADER,
  __module__ = 'types.proto3.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.types.proto3.PartSetHeader)
  ))
_sym_db.RegisterMessage(PartSetHeader)

BlockID = _reflection.GeneratedProtocolMessageType('BlockID', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKID,
  __module__ = 'types.proto3.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.types.proto3.BlockID)
  ))
_sym_db.RegisterMessage(BlockID)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'types.proto3.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.types.proto3.Header)
  ))
_sym_db.RegisterMessage(Header)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), dict(
  DESCRIPTOR = _VERSION,
  __module__ = 'types.proto3.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.types.proto3.Version)
  ))
_sym_db.RegisterMessage(Version)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'types.proto3.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.types.proto3.Timestamp)
  ))
_sym_db.RegisterMessage(Timestamp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
