# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/libs/bits/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/libs/bits/types.proto',
  package='tendermint.proto.libs.bits',
  syntax='proto3',
  serialized_options=_b('Z0github.com/tendermint/tendermint/proto/libs/bits'),
  serialized_pb=_b('\n\x1bproto/libs/bits/types.proto\x12\x1atendermint.proto.libs.bits\"\'\n\x08\x42itArray\x12\x0c\n\x04\x62its\x18\x01 \x01(\x03\x12\r\n\x05\x65lems\x18\x02 \x03(\x04\x42\x32Z0github.com/tendermint/tendermint/proto/libs/bitsb\x06proto3')
)




_BITARRAY = _descriptor.Descriptor(
  name='BitArray',
  full_name='tendermint.proto.libs.bits.BitArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bits', full_name='tendermint.proto.libs.bits.BitArray.bits', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elems', full_name='tendermint.proto.libs.bits.BitArray.elems', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['BitArray'] = _BITARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitArray = _reflection.GeneratedProtocolMessageType('BitArray', (_message.Message,), dict(
  DESCRIPTOR = _BITARRAY,
  __module__ = 'proto.libs.bits.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.libs.bits.BitArray)
  ))
_sym_db.RegisterMessage(BitArray)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
