# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/crypto/keys/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.third_party.proto.gogoproto import gogo_pb2 as third__party_dot_proto_dot_gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/crypto/keys/types.proto',
  package='tendermint.proto.crypto.keys',
  syntax='proto3',
  serialized_options=_b('Z2github.com/tendermint/tendermint/proto/crypto/keys'),
  serialized_pb=_b('\n\x1dproto/crypto/keys/types.proto\x12\x1ctendermint.proto.crypto.keys\x1a&third_party/proto/gogoproto/gogo.proto\"/\n\tPublicKey\x12\x11\n\x07\x65\x64\x32\x35\x35\x31\x39\x18\x01 \x01(\x0cH\x00:\x08\xe8\xa1\x1f\x01\xe8\xa0\x1f\x01\x42\x05\n\x03sum\"&\n\nPrivateKey\x12\x11\n\x07\x65\x64\x32\x35\x35\x31\x39\x18\x01 \x01(\x0cH\x00\x42\x05\n\x03sumB4Z2github.com/tendermint/tendermint/proto/crypto/keysb\x06proto3')
  ,
  dependencies=[third__party_dot_proto_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='tendermint.proto.crypto.keys.PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ed25519', full_name='tendermint.proto.crypto.keys.PublicKey.ed25519', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\241\037\001\350\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sum', full_name='tendermint.proto.crypto.keys.PublicKey.sum',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=103,
  serialized_end=150,
)


_PRIVATEKEY = _descriptor.Descriptor(
  name='PrivateKey',
  full_name='tendermint.proto.crypto.keys.PrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ed25519', full_name='tendermint.proto.crypto.keys.PrivateKey.ed25519', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sum', full_name='tendermint.proto.crypto.keys.PrivateKey.sum',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=152,
  serialized_end=190,
)

_PUBLICKEY.oneofs_by_name['sum'].fields.append(
  _PUBLICKEY.fields_by_name['ed25519'])
_PUBLICKEY.fields_by_name['ed25519'].containing_oneof = _PUBLICKEY.oneofs_by_name['sum']
_PRIVATEKEY.oneofs_by_name['sum'].fields.append(
  _PRIVATEKEY.fields_by_name['ed25519'])
_PRIVATEKEY.fields_by_name['ed25519'].containing_oneof = _PRIVATEKEY.oneofs_by_name['sum']
DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['PrivateKey'] = _PRIVATEKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), dict(
  DESCRIPTOR = _PUBLICKEY,
  __module__ = 'proto.crypto.keys.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.crypto.keys.PublicKey)
  ))
_sym_db.RegisterMessage(PublicKey)

PrivateKey = _reflection.GeneratedProtocolMessageType('PrivateKey', (_message.Message,), dict(
  DESCRIPTOR = _PRIVATEKEY,
  __module__ = 'proto.crypto.keys.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.crypto.keys.PrivateKey)
  ))
_sym_db.RegisterMessage(PrivateKey)


DESCRIPTOR._options = None
_PUBLICKEY._options = None
# @@protoc_insertion_point(module_scope)
