# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/types/block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.third_party.proto.gogoproto import gogo_pb2 as third__party_dot_proto_dot_gogoproto_dot_gogo__pb2
from tendermint.proto.types import types_pb2 as proto_dot_types_dot_types__pb2
from tendermint.proto.types import evidence_pb2 as proto_dot_types_dot_evidence__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/types/block.proto',
  package='tendermint.proto.types',
  syntax='proto3',
  serialized_options=_b('Z,github.com/tendermint/tendermint/proto/types'),
  serialized_pb=_b('\n\x17proto/types/block.proto\x12\x16tendermint.proto.types\x1a&third_party/proto/gogoproto/gogo.proto\x1a\x17proto/types/types.proto\x1a\x1aproto/types/evidence.proto\"\xe2\x01\n\x05\x42lock\x12\x34\n\x06header\x18\x01 \x01(\x0b\x32\x1e.tendermint.proto.types.HeaderB\x04\xc8\xde\x1f\x00\x12\x30\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1c.tendermint.proto.types.DataB\x04\xc8\xde\x1f\x00\x12<\n\x08\x65vidence\x18\x03 \x01(\x0b\x32$.tendermint.proto.types.EvidenceDataB\x04\xc8\xde\x1f\x00\x12\x33\n\x0blast_commit\x18\x04 \x01(\x0b\x32\x1e.tendermint.proto.types.CommitB.Z,github.com/tendermint/tendermint/proto/typesb\x06proto3')
  ,
  dependencies=[third__party_dot_proto_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,proto_dot_types_dot_types__pb2.DESCRIPTOR,proto_dot_types_dot_evidence__pb2.DESCRIPTOR,])




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='tendermint.proto.types.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tendermint.proto.types.Block.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='tendermint.proto.types.Block.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='tendermint.proto.types.Block.evidence', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_commit', full_name='tendermint.proto.types.Block.last_commit', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=371,
)

_BLOCK.fields_by_name['header'].message_type = proto_dot_types_dot_types__pb2._HEADER
_BLOCK.fields_by_name['data'].message_type = proto_dot_types_dot_types__pb2._DATA
_BLOCK.fields_by_name['evidence'].message_type = proto_dot_types_dot_evidence__pb2._EVIDENCEDATA
_BLOCK.fields_by_name['last_commit'].message_type = proto_dot_types_dot_types__pb2._COMMIT
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'proto.types.block_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.types.Block)
  ))
_sym_db.RegisterMessage(Block)


DESCRIPTOR._options = None
_BLOCK.fields_by_name['header']._options = None
_BLOCK.fields_by_name['data']._options = None
_BLOCK.fields_by_name['evidence']._options = None
# @@protoc_insertion_point(module_scope)
