# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/types/events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/types/events.proto',
  package='tendermint.proto.types',
  syntax='proto3',
  serialized_options=_b('Z,github.com/tendermint/tendermint/proto/types'),
  serialized_pb=_b('\n\x18proto/types/events.proto\x12\x16tendermint.proto.types\"B\n\x13\x45ventDataRoundState\x12\x0e\n\x06height\x18\x01 \x01(\x03\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\tB.Z,github.com/tendermint/tendermint/proto/typesb\x06proto3')
)




_EVENTDATAROUNDSTATE = _descriptor.Descriptor(
  name='EventDataRoundState',
  full_name='tendermint.proto.types.EventDataRoundState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='tendermint.proto.types.EventDataRoundState.height', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='tendermint.proto.types.EventDataRoundState.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='tendermint.proto.types.EventDataRoundState.step', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['EventDataRoundState'] = _EVENTDATAROUNDSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventDataRoundState = _reflection.GeneratedProtocolMessageType('EventDataRoundState', (_message.Message,), dict(
  DESCRIPTOR = _EVENTDATAROUNDSTATE,
  __module__ = 'proto.types.events_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.types.EventDataRoundState)
  ))
_sym_db.RegisterMessage(EventDataRoundState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
