# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/types/validator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.third_party.proto.gogoproto import gogo_pb2 as third__party_dot_proto_dot_gogoproto_dot_gogo__pb2
from tendermint.proto.crypto.keys import types_pb2 as proto_dot_crypto_dot_keys_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/types/validator.proto',
  package='tendermint.proto.types',
  syntax='proto3',
  serialized_options=_b('Z,github.com/tendermint/tendermint/proto/types'),
  serialized_pb=_b('\n\x1bproto/types/validator.proto\x12\x16tendermint.proto.types\x1a&third_party/proto/gogoproto/gogo.proto\x1a\x1dproto/crypto/keys/types.proto\"\x96\x01\n\x0cValidatorSet\x12\x35\n\nvalidators\x18\x01 \x03(\x0b\x32!.tendermint.proto.types.Validator\x12\x33\n\x08proposer\x18\x02 \x01(\x0b\x32!.tendermint.proto.types.Validator\x12\x1a\n\x12total_voting_power\x18\x03 \x01(\x03\"\x8d\x01\n\tValidator\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12>\n\x07pub_key\x18\x02 \x01(\x0b\x32\'.tendermint.proto.crypto.keys.PublicKeyB\x04\xc8\xde\x1f\x00\x12\x14\n\x0cvoting_power\x18\x03 \x01(\x03\x12\x19\n\x11proposer_priority\x18\x04 \x01(\x03\x42.Z,github.com/tendermint/tendermint/proto/typesb\x06proto3')
  ,
  dependencies=[third__party_dot_proto_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,proto_dot_crypto_dot_keys_dot_types__pb2.DESCRIPTOR,])




_VALIDATORSET = _descriptor.Descriptor(
  name='ValidatorSet',
  full_name='tendermint.proto.types.ValidatorSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validators', full_name='tendermint.proto.types.ValidatorSet.validators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposer', full_name='tendermint.proto.types.ValidatorSet.proposer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_voting_power', full_name='tendermint.proto.types.ValidatorSet.total_voting_power', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=277,
)


_VALIDATOR = _descriptor.Descriptor(
  name='Validator',
  full_name='tendermint.proto.types.Validator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='tendermint.proto.types.Validator.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='tendermint.proto.types.Validator.pub_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voting_power', full_name='tendermint.proto.types.Validator.voting_power', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposer_priority', full_name='tendermint.proto.types.Validator.proposer_priority', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=421,
)

_VALIDATORSET.fields_by_name['validators'].message_type = _VALIDATOR
_VALIDATORSET.fields_by_name['proposer'].message_type = _VALIDATOR
_VALIDATOR.fields_by_name['pub_key'].message_type = proto_dot_crypto_dot_keys_dot_types__pb2._PUBLICKEY
DESCRIPTOR.message_types_by_name['ValidatorSet'] = _VALIDATORSET
DESCRIPTOR.message_types_by_name['Validator'] = _VALIDATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValidatorSet = _reflection.GeneratedProtocolMessageType('ValidatorSet', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATORSET,
  __module__ = 'proto.types.validator_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.types.ValidatorSet)
  ))
_sym_db.RegisterMessage(ValidatorSet)

Validator = _reflection.GeneratedProtocolMessageType('Validator', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATOR,
  __module__ = 'proto.types.validator_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.types.Validator)
  ))
_sym_db.RegisterMessage(Validator)


DESCRIPTOR._options = None
_VALIDATOR.fields_by_name['pub_key']._options = None
# @@protoc_insertion_point(module_scope)
