# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/crypto/merkle/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/crypto/merkle/types.proto',
  package='tendermint.proto.crypto.merkle',
  syntax='proto3',
  serialized_options=_b('Z4github.com/tendermint/tendermint/proto/crypto/merkle'),
  serialized_pb=_b('\n\x1fproto/crypto/merkle/types.proto\x12\x1etendermint.proto.crypto.merkle\"M\n\x0bSimpleProof\x12\r\n\x05total\x18\x01 \x01(\x03\x12\r\n\x05index\x18\x02 \x01(\x03\x12\x11\n\tleaf_hash\x18\x03 \x01(\x0c\x12\r\n\x05\x61unts\x18\x04 \x03(\x0c\x42\x36Z4github.com/tendermint/tendermint/proto/crypto/merkleb\x06proto3')
)




_SIMPLEPROOF = _descriptor.Descriptor(
  name='SimpleProof',
  full_name='tendermint.proto.crypto.merkle.SimpleProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='tendermint.proto.crypto.merkle.SimpleProof.total', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='tendermint.proto.crypto.merkle.SimpleProof.index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaf_hash', full_name='tendermint.proto.crypto.merkle.SimpleProof.leaf_hash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aunts', full_name='tendermint.proto.crypto.merkle.SimpleProof.aunts', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['SimpleProof'] = _SIMPLEPROOF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleProof = _reflection.GeneratedProtocolMessageType('SimpleProof', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEPROOF,
  __module__ = 'proto.crypto.merkle.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.crypto.merkle.SimpleProof)
  ))
_sym_db.RegisterMessage(SimpleProof)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
