# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/statesync/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/statesync/types.proto',
  package='tendermint.proto.statesync',
  syntax='proto3',
  serialized_options=_b('Z0github.com/tendermint/tendermint/proto/statesync'),
  serialized_pb=_b('\n\x1bproto/statesync/types.proto\x12\x1atendermint.proto.statesync\"\xb0\x02\n\x07Message\x12I\n\x11snapshots_request\x18\x01 \x01(\x0b\x32,.tendermint.proto.statesync.SnapshotsRequestH\x00\x12K\n\x12snapshots_response\x18\x02 \x01(\x0b\x32-.tendermint.proto.statesync.SnapshotsResponseH\x00\x12\x41\n\rchunk_request\x18\x03 \x01(\x0b\x32(.tendermint.proto.statesync.ChunkRequestH\x00\x12\x43\n\x0e\x63hunk_response\x18\x04 \x01(\x0b\x32).tendermint.proto.statesync.ChunkResponseH\x00\x42\x05\n\x03sum\"\x12\n\x10SnapshotsRequest\"c\n\x11SnapshotsResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\x0e\n\x06\x63hunks\x18\x03 \x01(\r\x12\x0c\n\x04hash\x18\x04 \x01(\x0c\x12\x10\n\x08metadata\x18\x05 \x01(\x0c\"=\n\x0c\x43hunkRequest\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\r\"^\n\rChunkResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\r\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12\x0f\n\x07missing\x18\x05 \x01(\x08\x42\x32Z0github.com/tendermint/tendermint/proto/statesyncb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='tendermint.proto.statesync.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshots_request', full_name='tendermint.proto.statesync.Message.snapshots_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshots_response', full_name='tendermint.proto.statesync.Message.snapshots_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_request', full_name='tendermint.proto.statesync.Message.chunk_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_response', full_name='tendermint.proto.statesync.Message.chunk_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sum', full_name='tendermint.proto.statesync.Message.sum',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=60,
  serialized_end=364,
)


_SNAPSHOTSREQUEST = _descriptor.Descriptor(
  name='SnapshotsRequest',
  full_name='tendermint.proto.statesync.SnapshotsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=384,
)


_SNAPSHOTSRESPONSE = _descriptor.Descriptor(
  name='SnapshotsResponse',
  full_name='tendermint.proto.statesync.SnapshotsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='tendermint.proto.statesync.SnapshotsResponse.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='tendermint.proto.statesync.SnapshotsResponse.format', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='tendermint.proto.statesync.SnapshotsResponse.chunks', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='tendermint.proto.statesync.SnapshotsResponse.hash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='tendermint.proto.statesync.SnapshotsResponse.metadata', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=485,
)


_CHUNKREQUEST = _descriptor.Descriptor(
  name='ChunkRequest',
  full_name='tendermint.proto.statesync.ChunkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='tendermint.proto.statesync.ChunkRequest.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='tendermint.proto.statesync.ChunkRequest.format', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='tendermint.proto.statesync.ChunkRequest.index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=548,
)


_CHUNKRESPONSE = _descriptor.Descriptor(
  name='ChunkResponse',
  full_name='tendermint.proto.statesync.ChunkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='tendermint.proto.statesync.ChunkResponse.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='tendermint.proto.statesync.ChunkResponse.format', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='tendermint.proto.statesync.ChunkResponse.index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='tendermint.proto.statesync.ChunkResponse.chunk', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='missing', full_name='tendermint.proto.statesync.ChunkResponse.missing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=644,
)

_MESSAGE.fields_by_name['snapshots_request'].message_type = _SNAPSHOTSREQUEST
_MESSAGE.fields_by_name['snapshots_response'].message_type = _SNAPSHOTSRESPONSE
_MESSAGE.fields_by_name['chunk_request'].message_type = _CHUNKREQUEST
_MESSAGE.fields_by_name['chunk_response'].message_type = _CHUNKRESPONSE
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['snapshots_request'])
_MESSAGE.fields_by_name['snapshots_request'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['snapshots_response'])
_MESSAGE.fields_by_name['snapshots_response'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['chunk_request'])
_MESSAGE.fields_by_name['chunk_request'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['chunk_response'])
_MESSAGE.fields_by_name['chunk_response'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['SnapshotsRequest'] = _SNAPSHOTSREQUEST
DESCRIPTOR.message_types_by_name['SnapshotsResponse'] = _SNAPSHOTSRESPONSE
DESCRIPTOR.message_types_by_name['ChunkRequest'] = _CHUNKREQUEST
DESCRIPTOR.message_types_by_name['ChunkResponse'] = _CHUNKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'proto.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.statesync.Message)
  ))
_sym_db.RegisterMessage(Message)

SnapshotsRequest = _reflection.GeneratedProtocolMessageType('SnapshotsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SNAPSHOTSREQUEST,
  __module__ = 'proto.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.statesync.SnapshotsRequest)
  ))
_sym_db.RegisterMessage(SnapshotsRequest)

SnapshotsResponse = _reflection.GeneratedProtocolMessageType('SnapshotsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SNAPSHOTSRESPONSE,
  __module__ = 'proto.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.statesync.SnapshotsResponse)
  ))
_sym_db.RegisterMessage(SnapshotsResponse)

ChunkRequest = _reflection.GeneratedProtocolMessageType('ChunkRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHUNKREQUEST,
  __module__ = 'proto.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.statesync.ChunkRequest)
  ))
_sym_db.RegisterMessage(ChunkRequest)

ChunkResponse = _reflection.GeneratedProtocolMessageType('ChunkResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHUNKRESPONSE,
  __module__ = 'proto.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.proto.statesync.ChunkResponse)
  ))
_sym_db.RegisterMessage(ChunkResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
